config/routes.rb
Rails.application.routes.draw do
  resources :exchange_settings, except: :show
  devise_for :users, path: "users", path_names: {
    sign_in: "login",
    sign_out: "logout",
    # password: "secret",
    # confirmation: "verification",
    # unlock: "unblock",
    # registration: "register",
    sign_up: "signup",
    settings: "edit"
  }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
    get "edit", to: "devise/registrations#edit"
    get "logout", to: "devise/sessions#destroy"
  end
  resources :users, except: :index

  authenticated :user do
    root to: "exchange_settings#index", as: :authenticated_root
  end
  root to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange_setting.rb
# The settings contains the basic data for prediction
class ExchangeSetting < ApplicationRecord
  has_many :supported_currencies
  belongs_to :user
  validates :amount, presence: true
  validates :base_currency_id, presence: true
  validates :user_id, presence: true
  validates :period, inclusion: { in: 1..250 }, presence: true
  validates :target_currency_id, presence: true
end

app/models/supported_currency.rb
# Supported currencies, only the application user
# can extend this list (or a DB admin)
class SupportedCurrency < ApplicationRecord
  has_many :exchange_setting
  validates :currency_code, uniqueness: true, format: {
    with: /[A-Z]{3}/,
    message: "Only valid currency codes allowed"
  }
end

app/models/user.rb
# Users table model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false }
  has_many :exchange_settings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password, :remember_me]
  end
end

app/controllers/exchange_settings_controller.rb
# A logged in user can setup a new prediction settings
class ExchangeSettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :index, :update, :destroy]
  before_action :set_exchange_setting, only: [:edit, :update, :destroy]

  # GET /exchange_settings
  # GET /exchange_settings.json
  def index
    @exchange_settings = ExchangeSetting.where(user_id: current_user.id).order("id DESC")
  end

  # GET /exchange_settings/new
  def new
    @exchange_setting = ExchangeSetting.new
  end

  # GET /exchange_settings/1/edit
  # def edit
  # end

  # POST /exchange_settings
  # POST /exchange_settings.json
  def create
    @exchange_setting = ExchangeSetting.new(exchange_setting_params)
    if @exchange_setting.save
      flash[:success] = "The setting was successfully created."
      redirect_to exchange_settings_url
    else
      flash[:error] = "Please add correct values."
      redirect_to new_exchange_setting_url
    end
  end

  # PATCH/PUT /exchange_settings/1
  # PATCH/PUT /exchange_settings/1.json
  def update
    if @exchange_setting.update(exchange_setting_params)
      flash[:success] = "The setting was successfully updated."
      redirect_to exchange_settings_url
    else
      flash[:error] = "Please add correct values."
      redirect_to edit_exchange_setting_url(current_user.id)
    end
  end

  # DELETE /exchange_settings/1
  # DELETE /exchange_settings/1.json
  def destroy
    @exchange_setting.destroy
    flash[:success] = "The setting was successfully destroyed."
    redirect_to exchange_settings_url
  end

  private

  def set_user
    @user = current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_exchange_setting
    @exchange_setting = ExchangeSetting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exchange_setting_params
    params.require(:exchange_setting)
          .permit(:user_id, :base_currency_id, :target_currency_id, :amount, :period)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:create, :new]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :login]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def login
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render user_path, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to edit_user_path }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to new_user_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = "")
    base_title = "Money Exchange Predictor"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exchange_settings/edit.html.erb
<% provide(:title) %>

<div class="center jumbotron">
  <h2>
    Editing Exchange Setting
  </h2>
</div>

<%= render "shared/form_exchange_settings", exchange_setting: @exchange_setting %>
<%= render "shared/error_messages" %>

<%= link_to "Show", @exchange_setting %> |
<%= link_to "Back", exchange_settings_path %>

app/views/exchange_settings/index.html.erb
<% provide(:title) %>

<div class="center jumbotron">
  <h2>
    Your exchange settings
  </h2>
</div>

<table class="table">
  <thead>
    <tr>
      <th>
        <td>From currency</td>
        <td>To currency</td>
        <td>Exchange amount</td>
        <td>Prediction period</td>
        <td>Created date</td>
      </th>
    </tr>
  </thead>

  <tbody>
    <% count = 1 %>
    <% @exchange_settings.each do |exchange_setting| %>
      <tr>
        <td><%= link_to "#{count}. prediction", "#" %></td>
        <td><%= SupportedCurrency.find(exchange_setting.base_currency_id).currency_code %></td>
        <td><%= SupportedCurrency.find(exchange_setting.target_currency_id).currency_code %></td>
        <td><%= exchange_setting.amount %></td>
        <td><%= exchange_setting.period %></td>
        <td><%= exchange_setting.created_at.to_date %></td>
        <td><%= link_to "Edit", edit_exchange_setting_path(exchange_setting) %></td>
        <td><%= link_to "Destroy", exchange_setting, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
      <% count = count + 1 %>
    <% end %>
  </tbody>
</table>

<%= render "shared/error_messages" %>

<%= link_to "Setup a new prediction", new_exchange_setting_path %>

app/views/exchange_settings/new.html.erb
<% provide(:title) %>

<div class="center jumbotron">
  <h2>
    Prediction settings
  </h2>
</div>

<h4>Setup your preferencies for prediction</h4>

<%= render "shared/form_exchange_settings", user: current_user %>
<%= render "shared/error_messages" %>

<%= link_to "Back", exchange_settings_path %>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-text">
        <small>The Money Exchange Predictor by <a href="https://github.com/kilimandzsaro">Natalia Bakos</a>
        </small>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About",   '#' %></li>
        <li><%= link_to "Contact", '#' %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <% if current_user %>
    <nav>
      <ul class="nav navbar-nav navbar-header navbar-brand">
        Wellcome <%= current_user.name %> to Exchange Predictor
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "User Settings", edit_user_path(current_user.id) %></li>
        <li><%= link_to "Log out", logout_path %></li>
      </ul>
    </nav>
  <% else %>
    <nav>
      <ul class="nav navbar-nav navbar-header navbar-brand">
        Wellcome to Exchange Predictor
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Log in", login_path %></li>
      </ul>
    </nav>
  <% end %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  </br>
  <body>
    <div class="container", id="body">
      <%= render "layouts/header" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_exchange_settings.html.erb
<%= form_with(model: @exchange_setting, local: true) do |form| %>
  <%= render "shared/error_messages" %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table>
        <tr>
          <td><%= form.hidden_field :user_id, value: current_user.id %></td>
        </tr>
        <tr>
          <div class="form-inline">
            <td>
              <%= form.label :amount %>
            </td>
            <td>
              <div class="form-group">
                <%= form.number_field :amount, id: :amount, value: number_to_currency(form.object.amount.to_f, delimiter: "", unit: ""), step: :any, class: "form-control" %>
              </div>
            </td>
            <td>
              <div class="form-group">
                <%= form.collection_select :base_currency_id, SupportedCurrency.all, :id, :currency_code, { prompt: "Please select the base currency" }, class: "form-control" %>
              </div>
            </td>
          </div>
        </tr>
        <tr>
          <div class="form-inline form-group">
            <td>
              <%= form.label :target_currency %>
            </td>
            <td>
              <%= form.collection_select :target_currency_id, SupportedCurrency.all, :id, :currency_code, { prompt: "Please select the target currency" }, class: "form-control" %>
            </td>
          </div>
        </tr>
        <tr>
          <div class="form-inline form-group">
            <td>
              <%= form.label :period %>
            </td>
            <td>
              <%= form.range_field :period, in: 1..250, step: 1, id: :period, class: "form-control" %>
            </td>
          </div>
        </tr>
        <tr>
          <div class="form-inline form-group">
            <td><%= form.submit class: "btn btn-primary"%></td>
          </div>
        </tr>
      </table>
    </div>
  </div>
<% end %>

app/views/shared/_form_login.html.erb
<%= form_with(resource, as: resource_name, url: session_path(resource_name), html: { role: "form"}) do |form| %>
  <%= render "shared/error_messages" %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">   
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: "form-control" %>
      
      <%= form.label :password %>
      <%= form.password_field :password, id: :user_password, class: "form-control", autocomplete: "off" %>
      
      <% if devise_mapping.rememberable? %>
        <div class="ol-md-6 col-md-offset-3">
          <%= form.check_box :remember_me %>
          <%= form.label :remember_me %>
        </div>
      <% end %>

      <%= form.submit t(".sign_in", default: "Log in"), class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/shared/_form_signup.html.erb
<%= form_with model: user, local: true do |form| %>
  <%= render "shared/error_messages" %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form.label :name %>
      <%= form.text_field :name, id: :user_name, class: "form-control" %>
      
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: "form-control" %>
      
      <%= form.label :password %>
      <%= form.password_field :password, id: :user_password, class: "form-control" %>
      
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, id: :user_password_confirmation, 
        class: "form-control" %>

      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |form| %>
  <%= render "shared/error_messages" %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form.label :name %>
      <%= form.text_field :name, id: :user_name, class: "form-control" %>
      
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: "form-control" %>
      
      <%= form.label :password %>
      <%= form.password_field :password, id: :user_password, class: "form-control" %>
      
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, id: :user_password_confirmation, 
        class: "form-control" %>

      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title) %>
<div class="center jumbotron">
  <h1>
    Edit <%= @user.name %>
  </h1>
</div>

<%= render "shared/form_signup", user: @user %>

<%= link_to "Back", :back %>

app/views/users/new.html.erb
<% provide(:title) %>
<div class="center jumbotron">
  <h1>
    Sign Up
  </h1>
</div>
<div class="center jumbotron">
If you don't have a user, please sign up first. If you have than please <%= link_to "login", new_user_session_path %>
</div>

<%= render "shared/form_signup", user: @user %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="center jumbotron">
  <h1>
    Wellcome to my calculator <%= @user.name %>!
  </h1>
</div>
<%= render "shared/error_messages" %>

<%= link_to "Edit", edit_user_path(@user) %>